project:
  type: book
  output-dir: docs
  resources:
    - pdf
    - xkcd

book:
  title: "Field Guide to Mathematics at Southampton"
  author: "First Year Student 25/26"

  sidebar:
    search: true
    tools:
      - icon: download
        href: assets/field-guide.pdf
        text: Download PDF

      - icon: link 
        href: https://www.southampton.ac.uk/about/faculties-schools-departments/school-of-mathematical-sciences
        text: School of Mathematical Sciences 

  chapters:
    - index.qmd
    - chapters/01-the jump to university.qmd
    - chapters/02-lectures and coursework.qmd
    - chapters/03-workshops and other resources.qmd
    - chapters/04-problem Solving.qmd
    - chapters/05-exams.qmd
    - chapters/06-time Management.qmd
    - chapters/07-future.qmd
    - chapters/08-useful Links.qmd

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    include-in-header:
      - text: |
          <script>
          document.addEventListener("scroll", () => {
            const scrollTop = document.documentElement.scrollTop;
            const height =
              document.documentElement.scrollHeight -
              document.documentElement.clientHeight;
            const scroll = height > 0 ? scrollTop / height : 0;
            document.body.style.setProperty("--scroll", scroll);
          });
          </script>
    toc: true
    number-sections: true
    search: true
    respect-user-color-scheme: true
    page-navigation: true
