project:
  type: book
  output-dir: docs

book:
  title: "Field Guide to Mathematics at University" 
  author: "First Year Student 25/26"
  chapters:
    - index.qmd
    - chapters/01-the-jump.qmd
    - chapters/02-lectures-and-coursework.qmd
    - chapters/03-workshops-and-other-resources.qmd
    - chapters/04-problem-solving.qmd
    - chapters/05-exams.qmd
    - chapters/06-time-management.qmd
    - chapters/07-future.qmd
    - chapters/08-useful-links.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    search: true
    number-sections: true
